### PR TITLE
Initial workshops

### PR DESCRIPTION
**Pull request by kolber**
Could you see if you can cut down to bios to around 260–280 chars @robrkerr?
And if you want you can add descriptions to the workshops html. 💯

### CODE REVIEW

**Comment by robrkerr** [comment]
@kolber done! Let me know what you think - oh and I renamed the file for the phonegap SVG (strangely this fixed an issue where it was being removed by an adblocker).

**Comment by kolber** [comment]
Looks good @rob, I just removed the `<b>`s for consistency with the other sites.
Ready to merge. Feel free to hit the green button whenever you're ready!

**Comment by robrkerr** [comment]
Thanks @kolber. I'll go over it early tomorrow with Isabell and probably merge it in then. Thanks for your help!

**Comment by kolber** [comment]
Perfect, thanks Rob!

**Pull request merged**
