### PR TITLE
New speakers - Cathy and Rick

### PR DESCRIPTION
**Pull request by robrkerr**
All ready to announce two more speakers

### CODE REVIEW

**Comment by kolber** [comment]
Beautiful.

**Comment by robrkerr** [comment]
sorry @kolber we weren't actually ready to do this - I was just setting it up for when we were (in retrospect that was a bit dumb of me) - I'll revert it now

**Comment by kolber** [comment]
Oops, sorry! I went on a merging rampage.
Maybe add a [WIP] to the PR title so we know these things aren't ready to go yet. :)

**Comment by robrkerr** [comment]
No problem.

**Pull request merged**
